

const supabaseUrl = 'https://xnfpsjvlrfvfjdsidxrz.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZnBzanZscmZ2Zmpkc2lkeHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNzg3OTQsImV4cCI6MjA1Njk1NDc5NH0.rmeZw5GPF1NpNsgzXw_MnMBj_asF2Xv2eKXV5kLbmbE'



// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { supabase } from "@/integrations/supabase/client";
import type { Database } from './types';

const SUPABASE_URL = "https://xnfpsjvlrfvfjdsidxrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZnBzanZscmZ2Zmpkc2lkeHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNzg3OTQsImV4cCI6MjA1Njk1NDc5NH0.rmeZw5GPF1NpNsgzXw_MnMBj_asF2Xv2eKXV5kLbmbE";

// Import the supabase client like this:

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

const supabase = createClient(supabaseUrl, supabaseKey)
